### ISSUE TITLE
Black screen problem

### ISSUE THREAD

**Issue by netmediasurfer** [legostax/lightdm-webkit-chromium#3] opened 2017-11-21 04:36 UTC
Hi, I'm able to get this cool chromium theme working with all Ubuntu versions up to 15.10 Wily. However, I'm unable to get it working on Ubuntu 16, 17 or 18.

Can you please update the code to function with these versions of Ubuntu. I have tried everything I could think of to make it work but I have been unsuccessful. I tried other webkit-greeter themes to make sure the lightdm-webkit-greeter was working & those seem to work without a problem. 

However, the ones I tried don't have the ability to switch sessions via their GUI so I'm thinking that may be the cause. I don't know how to fix that with the chromium theme. Can you please look into that.

I have Ubuntu 16.04 with "lightdm-webkit-greeter"  version 0.1.2-0ubuntu3 installed.

Thanks!

**Comment by tyrumus** [comment] 2017-11-23 22:50
@netmediasurfer Sorry for not responding sooner, been busy with school.  I have this set up and running fine on Ubuntu 16.04 LTS.

What specifically is the problem with switching sessions?  Are the desktop files located at `/usr/share/xsessions/` appearing in the list?  If not, then there's a place to start.  If so, what happens when you select one and login?  Does LightDM crash?  Does `lightdm-webkit-greeter` crash?  Knowing exact specifics would help me figure out your problem a lot faster.  We're using the same versions of Ubuntu and the webkit greeter.

Right now, I don't have much to go on, considering I can't reproduce your problem myself. :)

**Comment by netmediasurfer** [comment] 2017-11-23 23:41
Hi, happy holidays!

Chromium theme doesn't load at all on Ubuntu 16.04. I get a black screen. 

To get back into the LXDE desktop I have to press ctrl+alt+f1 to edit /etc/lightdm.conf to use the "lightdm-gtk-greeter" temporarily & run sudo service lightdm restart to regain login access via the login gui.

Can you please tell me what your permissions are set to.

Kindly go to ..

cd /etc/lightdm-webkit/themes/chromium

run 

sudo stat -c "%a%n" *

That should display permissions for files & directories.

I used UBUNTU 16.03 64X iso & updated it to 16.04 via apt-get. I don't have any weird errors poping up ect ..


Thank you!

**Comment by tyrumus** [comment] 2017-11-23 23:49
Output of `stat -c "%a%n" *` (you don't need sudo, and you can accomplish this with `ls -l`)
```
755assets
644index.html
644index.theme
644LICENSE
644README.md
```

But, I don't think file permissions are your problem.  You told me to go to `/etc/lightdm-webkit/themes/chromium` so I assume that's where you cloned this repository to use it as a theme.  You should have cloned it to `/usr/share/lightdm-webkit/themes/`.  [Try following these instructions.](https://github.com/legostax/lightdm-webkit-chromium/wiki/Installation)

**Comment by netmediasurfer** [comment] 2017-11-24 00:33
Hi, thanks. I'll try a fresh install.

ls -l 

Doesn't display numeric values for me.  It displays the permissions in non numeric fashion but it's easier for me to see it as numbers which is why I use the stat -c command.

Thank you

**Comment by tyrumus** [comment] 2017-11-24 00:35
Ah, makes sense. :) Happy to help! Let me know if the fresh install goes well so I can close the issue.

**Comment by tyrumus** [comment] 2017-11-24 14:39
Assuming this was a bad install problem and nothing more.  Closing.

**Comment by netmediasurfer** [comment] 2017-11-24 22:13
Hi, here are my findings ..

I got it working on a fresh install but with the following permissions but it still hangs.

777 lightdm-webkit-chromium

755 assets
755 index.html
755 index.theme
644 LICENSE
644 README.md

Within "assets" all .js files were chmodded to 755

Restarted lightdm service & the theme showed up this time on UBUNTU 16.04.3 LTS 32X

I think the issue was that I was chmodding "main.css" within the assets directory to 755 instead of leaving it as 644. "Roboto-Regular.ttf" must also remain as 644.


I edited the "main.css" file to use a custom background ...

wallpaper.png

I restart lightdm & I get the black screen with the white pointer only. I press ctrl alt F1 to get a terminal & change "main.css" to use the default wallpaper.jpg again. Restart lightdm service & again I get the black screen with white pointer only.

I don't understand why it hangs but after restarting the lightdm service a few more times it works again until I attempt to log in & out a few times.

I'm using the following ..

UBUNTU 16.04.3 32X
KERNEL: 4.1.0-28-generic i686
lightdm-webkit-greeter = 0.1.2-0ubuntu3


Thank you

**Comment by tyrumus** [comment] 2017-11-25 14:53
I don't understand why you'd have to change the file permissions at all.  None of the files in my `/usr/share/lightdm-webkit/themes/lightdm-webkit-chromium` are executable.  All are set to 644, including those in `assets`.

Don't know if this is related, but when I run `uname -r` it tells me my kernel version is `4.10.0-40-generic`.

Even with the fresh install it's still hanging?  Have you ever ran `sudo dpkg-reconfigure lightdm`?

When you change to using the custom background, is that file's permissions set to 644?

Upon further internet searching, [here's a bug](https://bugs.launchpad.net/lightdm-webkit-greeter/+bug/1154065) with `lightdm-webkit-greeter` that is similar to your problem.  The fix was released in Ubuntu Yakkety.  Xenial was skipped over.  But I don't run into this issue.  I'm assuming that's because I never run `sudo systemctl restart lightdm`.  I just tried it myself and was able to change the wallpaper from the default without restarting the display manager.  Regardless, this still doesn't fix the hanging problem that you say happens even with the fresh install, but it's a start.

**Comment by netmediasurfer** [comment] 2017-11-27 22:51
Seems to be stable now. The initial issue was being caused by the GDM greeter. Once I started fresh & avoided installing the GDM greeter, LIGHTDM began working properly again. I think end users now have to choose one or the other. Installing both greeters causes webkit-greeter loading issues. At least this is the case for UBUNTU 16+.


Thanks! 

Take care


 

 

 

-----Original Message-----

**Comment by tyrumus** [comment] 2017-11-27 22:53
Ah, I see.  I was pretty sure it wasn't an issue with _my_ code.  I've never really messed around with GDM, so I wouldn't know.  Glad you were able to figure it out!  Cheers!

**Closed as completed by tyrumus** 2017-11-27 22:53 UTC
Labels: help wanted
